manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: art-display
    #   url-base: https://github.com/PowerAbuser
    - name: m165437 #new entry
      url-base: https://github.com/M165437 #new entry
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
  #  - name: gpeye
  #    url-base: https://github.com/GPeye

  projects:
    # - name: mario-peripheral-animation
    #   remote: gpeye
    #    revision: main
    - name: eyelash_sofle
      url: https://github.com/a741725193/zmk-sofle
      revision: main
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    # - name: zmk-sofle
    #   remote: art-display
    #   revision: main
    - name: nice-view-gem #new entry
      remote: m165437 #new entry
      revision: v0.3.0 #new entry
  self:
    path: boards
